### ISSUE TITLE
Styling with colorAccent instead of colorPrimary

### ISSUE THREAD

**Issue by grantbdev** [braintree/android-card-form#1]
According to Google's spec (https://www.google.com/design/spec/style/color.html#color-ui-color-application) the app theme's colorAccent should set the color of UI controls such as text fields. Using colorPrimary for the focused color on the card form makes it inconsistent with the other text fields in the app.

**Comment by lkorth** [comment]
Right you are. 

I've made the correction and released it in `2.0.1`.

Thanks for the report!
