### ISSUE TITLE
Legacy Visa icon need to be updated

### ISSUE THREAD

**Issue by MohamedISoliman** [braintree/android-card-form#103]
Can you please update Visa icon with the newest one?

**Comment by sarahkoop** [comment]
Hi @MohamedISoliman, we are looking into the current brand guidelines to resolve this issue.

**Comment by imohamedsoliman** [comment]
@sarahkoop is there any updates about this

**Comment by sarahkoop** [comment]
This change has been released in version [5.1.0](https://github.com/braintree/android-card-form/releases/tag/5.1.0) of `android-card-form`.
