### ISSUE TITLE
Proguard support.

### ISSUE THREAD

**Issue by fodawim** [braintree/android-card-form#11]
No mention of proguard issues so far, but enabling proguard would fail for me.

Added the following to my proguard rules and all seemed fine. 

Might be useful to add to the readme. Note that I do not have card.io imported into the project, so this rule might not work for those with card.io support.

`-dontwarn io.card.payment.**`

**Comment by lkorth** [comment]
@fodawim thanks for the letting us know. I've pushed a fix for this to `master`.
