### ISSUE TITLE
Can't change text color and edittext background color

### ISSUE THREAD

**Issue by ArjunPatidar-numero** [braintree/android-card-form#110]
### General information

* SDK/Library version: 
* Android Version and Device: 

### Issue description

As I wan to use this card from and my screen background is black and the card form text color is also black, I don't even see the card form in App.

**Comment by sarahkoop** [comment]
Hi @ArjunPatidar-numero, please see the [Styling section of the README ](https://github.com/braintree/android-card-form#styling) for details on styling card form for your application. We also provide a [sample app](https://github.com/braintree/android-card-form/tree/master/Sample) with both light theme and dark theme as a guide that may help. If the issue persists, please re-open this issue including details about which SDK version you are using and the `styles.xml` file you have configured.
