### ISSUE TITLE
Purchase Button not visible

### ISSUE THREAD

**Issue by sivailangos** [braintree/android-card-form#12]
Purchase button is not visible on the bottom of the Card form, below is the snipped I have used, it shows only Card Form

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_credit_card_form);

        cardForm = (CardForm) findViewById(R.id.bt_card_form);
        cardForm.setRequiredFields(CreditCardFormActivity.this, true, true, true, true, "Purchase");
        cardForm.setOnCardFormSubmitListener(this);

**Comment by lkorth** [comment]
There is no button included with the card form, the string that is supplied is for the IME submit label on the keyboard. It is up to you to supply a button.
