### ISSUE TITLE
Textfields location

### ISSUE THREAD

**Issue by dierivera** [braintree/android-card-form#13]
is there a way to move the expiration date field next to the card field?

**Comment by lkorth** [comment]
In the pending 3.x branch the expiration date field and the cvv field are now on the same line when they are both present. Combining the expiration date field and the card number field on the same line when the cvv field is not present would result in a very complex layout and logic.

**Comment by dierivera** [comment]
And is there a way to add a button next to the card field, for example for the scan button. Just like the uber app?

And yes, I was thinking of date and cvv, not card field, my bad.
Is the 3.x branch going to be released soon? I tried to search it in the git but the last is 2.X

**Comment by lkorth** [comment]
3.x has already been merged to master and will be tagged and released soon.

It's up to you to add a button to trigger card scanning. There is an [icon included in the library](https://github.com/braintree/android-card-form/blob/db8444e5bac539b0526ff450f6d04ca244c157cc/CardForm/src/main/res/drawable-xxxhdpi/bt_ic_camera.png) that may be useful to use as your button. The sample app [includes a button in the toolbar](https://github.com/braintree/android-card-form/blob/db8444e5bac539b0526ff450f6d04ca244c157cc/Sample/src/main/res/menu/card_io.xml) to trigger card scanning.

**Comment by dierivera** [comment]
Yes i've seen the icon (I implemented the option menu with the scan option with the icon) but i was thinking on something like this: (where the scan button is next to the card field
![screenshot_2016-09-29-16-13-10](https://cloud.githubusercontent.com/assets/8505619/18974356/cd16e63a-865f-11e6-8673-ba3b91d1ba12.png)

**Comment by lkorth** [comment]
There's nothing built into the library that would support that, you'd need to modify the layout and extend the `CardForm` class yourself.
