### ISSUE TITLE
Displaying errors in custom EditTexts doesn't work

### ISSUE THREAD

**Issue by jcloquell** [braintree/android-card-form#15]
When trying to set an error to one of the custom EditTexts (like CardEditText, CvvEditText...), assuming that they are wrapped around a `TextInputLayout` nothing is displayed in the UI. Looking at the code I found that the problem is in the `ErrorEditText` class. The method to get the parent TextInputLayout has a bug:

```
public TextInputLayout getTextInputLayoutParent() {
        if (getParent() != null && getParent().getParent() instanceof TextInputLayout) {
            return (TextInputLayout) getParent().getParent();
        }
        return null;
    }
```

it's trying to get the parent of the parent, when it should be directly the parent:

```
public TextInputLayout getTextInputLayoutParent() {
        if (getParent() != null && getParent() instanceof TextInputLayout) {
            return (TextInputLayout) getParent();
        }
        return null;
    }
```

it's an easy fix, if I have time I'll create a PR.

**Comment by lkorth** [comment]
@jcloquell: It depends on what version of the design support library you are using. The card form requires [24.2.1+](https://github.com/braintree/android-card-form/blob/master/CardForm/build.gradle#L36) because in 24.2.0 an additional frame was added to `TextInputLayout` and thus why we are using `getParent().getParent()`.

**Comment by jcloquell** [comment]
@lkorth 👍 I'm still using version 23, so makes sense. I wasn't aware of that change in the design library. Thanks for the fast reply :)

**Comment by lkorth** [comment]
I'm a little surprised that gradle handled the dependency in that way. I wonder if it has to do with `android-card-form` using a range for the design support library.

**Comment by jcloquell** [comment]
No, gradle complained, but I didn't want to update to version 24+ yet, so I'm excluding the design module from the `android-card-form` dependency. I'll update soon to 24 so I guess some small issues I'm having will be resolved.

**Comment by lkorth** [comment]
Ah, ok. That makes sense. Thanks for the info.

Let us know if you run into any other issues.
