### ISSUE TITLE
Font size for year selector.

### ISSUE THREAD

**Issue by teddywilson** [braintree/android-card-form#16]
Any way you could modify the font size on the expiration keyboard so that the yearly dates don't overflow into two lines?

**Comment by lkorth** [comment]
@teddywilson are you talking about in landscape? Do you have a screenshot to show as an example?

**Comment by teddywilson** [comment]
<img width="178" alt="screen shot 2016-10-27 at 3 41 36 pm" src="https://cloud.githubusercontent.com/assets/10104111/19782452/e2534f9a-9c5b-11e6-962f-7349b721baa3.png">

So I can't do it on my phone because it says it's a DRM protected image, but image the year column in this screenshot but the text overlapping into two rows.

So the entries look like this:

201
4
201
5
201
6
... 

I'm using a samsung galaxy s4, which isn't too small. I hope this helps!

**Comment by lkorth** [comment]
Justs a note: the card form sets `FLAG_SECURE` to prevent screenshots by malicious apps of the user's card information. The sample app in this repo does disable it for testing purposes however.

Thanks for the example, I know exactly what you mean. We'll take a look at fixing this.

**Comment by teddywilson** [comment]
Thank you!
