### ISSUE TITLE
Function returns null string

### ISSUE THREAD

**Issue by joeljoy** [braintree/android-card-form#2]
```java
mCardForm = (CardForm) findViewById(R.id.card_form);
mCardForm.setRequiredFields(this, true, true, true, true, getString(R.string.purchase));
mCardForm.setOnCardFormSubmitListener(this);

CardNumber = mCardForm.getCardNumber();
ExpirationMonth = mCardForm.getExpirationMonth();
ExpirationYear = mCardForm.getExpirationYear();
Cvv = mCardForm.getCvv();
 PostelCode = mCardForm.getPostalCode();
```

Above functions return null strings.

**Comment by grantbdev** [comment]
They are returning null probably because no text has been put in the field yet if you're getting the values right after creating the card form. You can override onCardFormSubmit() and then once the user submits the form you can check that the form is valid and get the values.

**Comment by lkorth** [comment]
@grantbdev is correct, you'll want to make sure that the user has typed something or submitted the form. Under the hood these are just `TextView`s and will return null if no value has been entered into them. 
There are [tests](https://github.com/braintree/android-card-form/blob/master/CardForm/src/androidTest/java/com/braintreepayments/cardform/view/CardFormTest.java#L160-L203) for the `CardForm` class to make sure that they do always return the values correctly.
