### ISSUE TITLE
Display the keyboard purchase button when postal code and phone number are disabled

### ISSUE THREAD

**Issue by bisonfute** [braintree/android-card-form#20]
Hi there and thanks for your library, it is great!

I use it this way
```
creditCardForm.cardRequired(true)
                .expirationRequired(true)
                .cvvRequired(true)
                .postalCodeRequired(false)
                .mobileNumberRequired(false)
                .actionLabel("DONE")
                .setup(AccountCreationActivity.this);
```

But the keyboard DONE button doesn't display when I am on the cvv edittext. Is there any way to do it ?

Regards.

**Comment by lkorth** [comment]
@bisonfute do you have a screenshot or any more info regarding the version of the card form you are using or the device you are seeing it on? Do note that the keyboard is not obligated to display this, if you're using a third party keyboard they may not ever display action labels like this.

The sample app that is include works just fine with the configuration you described and there are also [tests for this scenario](https://github.com/braintree/android-card-form/blob/1f8c2ffa5f040ae5b1a2f6fd60af0a5444e45d66/CardForm/src/test/java/com/braintreepayments/cardform/view/CardFormTest.java#L243).

<img width="271" alt="screenshot 2016-11-17 10 04 36" src="https://cloud.githubusercontent.com/assets/1163999/20394414/6c49503a-acad-11e6-8b52-83ea98af9f62.png">

**Comment by bisonfute** [comment]
@lkorth thanks for your answer.
I reproduce the issue using the sample app and configuring it like this
```
mCardForm.cardRequired(true)
                .expirationRequired(true)
                .cvvRequired(true)
                .postalCodeRequired(false)
                .mobileNumberRequired(false)
                .mobileNumberExplanation("Make sure SMS is enabled for this mobile number")
                .actionLabel(getString(R.string.purchase))
                .setup(this);
```
the result looks like this.
![image](https://cloud.githubusercontent.com/assets/11193622/20431332/c76065a2-ad99-11e6-8079-cb803ced13cd.png)

The phone is a samsung S4 and the langage is set to french.

I tried to set the language to English(US) to this one and the result is the same : 

![image](https://cloud.githubusercontent.com/assets/11193622/20431261/7d30f7c6-ad99-11e6-921e-6f5bb0424dc8.png)

**Comment by bisonfute** [comment]
The issue might come from the keyboard that is not the Android default one but a Samsung custom one. I confirm that on a Nexus simulator everything works fine.

**Comment by lkorth** [comment]
Yeah, it may just be the keyboard you're using is reading the IME options incorrectly. One thing you could try is changing how the [IME options and action label is set](https://github.com/braintree/android-card-form/blob/1f8c2ffa5f040ae5b1a2f6fd60af0a5444e45d66/CardForm/src/main/java/com/braintreepayments/cardform/view/CardForm.java#L220-L221) to see if the keyboard is placing more importance on the options than the action label. It may be that removing the IME options will get the action label to display for you.

**Comment by bisonfute** [comment]
I will try this, ok, thanks. I'll let you know in this Github Issue what results I did get.
For information, this keyboard is installed and set up by default on all Samsung Android devices.

**Comment by bisonfute** [comment]
I confirm the issue comes from the default samsung keyboard. I didn't find any workaround, so the best option is to deal with it and adapt UI.
Thanks @lkorth !
