### ISSUE TITLE
Hide credit card icon?

### ISSUE THREAD

**Issue by carlastabile** [braintree/android-card-form#22]
Hello, is there a way to hide the credit card icon? I've been searching in the source code but the attribute is private and there's no getter or anything. Having the option of hiding it would be nice 😄 

Thanks for the lib!

this is the icon:
![screen shot 2016-12-29 at 4 39 26 pm](https://cloud.githubusercontent.com/assets/2745491/21547303/79eaa6d6-cde5-11e6-9a0e-1422aa3cc654.png)

**Comment by sdcoffey** [comment]
Hey @carlastabile,

Thanks for the feedback! Great idea. How would you feel about an API where we allowed you set your own drawable resource for all of the fields in the form, or pass `null` to hide the field.

Something like:

```java
setCardNumberIcon(Integer drawableRes) {
    if (drawableRes == null) {
          mCardNumberIcon.setVisibility(View.GONE);
    } else {
          mCardNumberIcon.setImageResource(drawableRes);
    }
}
```

**Comment by carlastabile** [comment]
@sdcoffey that will work for me! Specially because we can "re-use" the form and set different icons so designers are happy with it haha. Any idea when this could be available? Thanks for the quick reply.

**Comment by sdcoffey** [comment]
Cool, that seems to make the most sense to me too. I'll add this stream of work to our queue and tag you in the PR when we have something ready to look at. Thanks again for helping us improve this library!
