### ISSUE TITLE
ExpirationDateDialog allows only 10 years in advance (vs. 20 in DateValidator)

### ISSUE THREAD

**Issue by hellmund** [braintree/android-card-form#25]
We have some users who are unable to select their credit card's expiration date through `ExpirationDateDialog` - in case the expiration date is >10 years in the future. Meanwhile, the corresponding client-side validator technically allows for 20 years (see `com.braintreepayments.cardform.utils.DateValidator.MAXIMUM_VALID_YEAR_DIFFERENCE`)

Possible fix:
- remove hard-coded magic number `10` in `com.braintreepayments.cardform.view.ExpirationDateDialog.java:L91`
- replace with reference to `MAXIMUM_VALID_YEAR_DIFFERENCE` in DateValidator, change its visibility to public

**Comment by lkorth** [comment]
Thanks for pointing this out @hellmund. I've updated it to use `DateValidator.MAXIMUM_VALID_YEAR_DIFFERENCE`.

This will go out in the next release.
