### ISSUE TITLE
I want to set CVV input type as password

### ISSUE THREAD

**Issue by Snehal-Tembare** [braintree/android-card-form#28]
### General information

* SDK/Library version: 3.0.5
* Android Version and Device: Genymotion 5.0.0

### Issue description
I am trying to set CVV input type as password but its not working for me.

**Comment by lkorth** [comment]
@Snehal-Tembare care to share how you're attempting to do it?

All you need to do is the following after the card form is set up:

```java
cardForm.getCvvEditText().setInputType(InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_VARIATION_PASSWORD);
```

**Comment by Snehal-Tembare** [comment]
Thanks.
But one more issue now I am facing is that its not working in AndroidStudio version to 3.0.

**Comment by lkorth** [comment]
Please see #30 for AAPT2 issues in Android Studio 3.0 Canary builds or open a new issue.
