### ISSUE TITLE
Android build error while using AAPT2

### ISSUE THREAD

**Issue by vverbytskyi** [braintree/android-card-form#30]
### General information

* SDK/Library version: drop-in:3.0.8
* Android build tools version: 26.0.0
* Android Gradle plugin version: 3.0.0-alpha3

### Issue description
When I'm trying to build an APK, that contains "drop-ui" library, I am receiving next issue 
`Error: values.xml:3821 (integer) -1 is less than minimum integer 0`
Opening this file gives me next results:

`<style name="bt_expiration_date_dialog_grid_view">
   /*other parameters*/
<item name="android:numColumns">auto_fit</item>
</style>`

Here is interesting the next line `<item name="android:numColumns">auto_fit</item>`.
[Android](https://developer.android.com/reference/android/widget/GridView.html#AUTO_FIT) docs say, that "auto_fit" parameter has value "-1", but seems AAPT2 can't merge integers that contains values less than 0

**Comment by lkorth** [comment]
I encounter a similar error when compiling with the alpha build plugin.

It seems a bit like this is a bug in AAPT2 if it can't handle valid (-1) Android values. Given the alpha nature of these tools, we're happy to accept any workarounds you may have, but we'll probably wait until they mature a bit before upgrading to and supporting them.

**Comment by lkorth** [comment]
android-card-form is currently being build with v25.x of the support library, in v26 `auto_fit` was changed to avoid this error. Until v26 of the support library comes out of beta and android-card-form can be updated to use it, please add `android.enableAapt2=false` to your `gradle.properties` file to avoid this error.
