### ISSUE TITLE
Is it possible to change Postal Code to Zip Code

### ISSUE THREAD

**Issue by MmtBkn** [braintree/android-card-form#32]
Hello,

I need to replace 'Postal Code' with 'Zip Code'.

I'm able to get editText using the following, but I think hint is set at EditTextLayout.

`cardForm.getPostalCodeEditText()`

Thank you.

**Comment by lkorth** [comment]
You just need to call [`setFieldHint`](https://github.com/braintree/android-card-form/blob/15512e76b7c2600e41f7ced2206585e3181900e2/CardForm/src/main/java/com/braintreepayments/cardform/view/ErrorEditText.java#L73) on the `PostalCodeEditText`.
