### ISSUE TITLE
Updating outdated MasterCard logo

### ISSUE THREAD

**Issue by mrsasha** [braintree/android-card-form#34]
Hi,

I noticed that you're still using the old MasterCard logo, which got changed last year. Can we get this updated please?

http://www.underconsideration.com/brandnew/archives/new_logo_and_identity_for_mastercard_by_pentagram.php
https://brand.mastercard.com/brandcenter/mastercard-brand-mark.html

Thanks!

**Comment by lkorth** [comment]
Not sure why GitHub failed to reference the commit 24fcc5ae435e6406cc12eae67bf725cf1ba2bc9e

**Comment by mrsasha** [comment]
thanks!
