### ISSUE TITLE
Question: how to know if it's a debit card or credit card?

### ISSUE THREAD

**Issue by yuanliu666** [braintree/android-card-form#37]
### General information

* SDK/Library version: 3.3.0
* Android Version and Device: Google Nexus 6P API 27

### Issue description
Hi, nice library! However is there any way for me to know if input card is a debit card or credit card? Thanks!

**Comment by quinnjn** [comment]
Hi! Thanks!!

This library only determines identification from the Card Number. I don't think there is a way to tell between if the card is debit until you process the card transaction. 

At transaction, Braintree can tell you BIN data such as [if the card is debit](https://developers.braintreepayments.com/reference/response/payment-method-nonce/java#bin_data.debit).
