### ISSUE TITLE
The ability to add new fields to the form.

### ISSUE THREAD

**Issue by omar753sahl** [braintree/android-card-form#39]
### Issue description

Having the ability to add new fields to the form would be great. 
For example, some forms need to include a field for "Card Holder Name".

**Comment by quinnjn** [comment]
We have an old pull request for this. Reviving #19

**Comment by omar753sahl** [comment]
Is it done? which version?

**Comment by omar753sahl** [comment]
I see that Travis build failed for that PR.

**Comment by quinnjn** [comment]
The pull request is pretty old, Nov 2016. It will take some time to get it up to date.

**Comment by quinnjn** [comment]
#51 has been merged into `master` and is available as a snapshot:
```
implementation 'com.braintreepayments:card-form:3.4.2-SNAPSHOT'
```

**Comment by quinnjn** [comment]
android-card-form 3.5.0 has been released which has this feature.
```
implementation 'com.braintreepayments:card-form:3.5.0'
```
