### ISSUE TITLE
Cant take screenshots

### ISSUE THREAD

**Issue by Sutheres** [braintree/android-card-form#44]
### Issue description

I put `getWindow().clearFlags(WindowManager.LayoutParams.FLAG_SECURE);`in onCreate of my Activity that holds the cardForm. Still cannot take screenshots. Am I missing something?

**Comment by quinnjn** [comment]
This should work. It should be after the `CardForm#setup(Activity)`. That method is where the `FLAG_SECURE` gets set.

Even without this line, you should be able to take screenshots using an emulator.

You'll want to be careful with releasing your Android app that has this flag cleared. Ideally production apps shouldn't be able to take screenshots.

**Comment by crookedneighbor** [comment]
For reference: https://github.com/braintree/android-card-form/blob/960d8af2abe69cd369bb0ade8ee4bb500de35a0b/CardForm/src/main/java/com/braintreepayments/cardform/view/CardForm.java#L205
