### ISSUE TITLE
Support card.io

### ISSUE THREAD

**Issue by lkorth** [braintree/android-card-form#5]
Either directly through integrating with card.io or expose setters for the fields in the `CardForm` class.

Brought up in https://github.com/braintree/braintree_android/issues/82

**Comment by HarryMMR** [comment]
Is this feature added yet?

**Comment by lkorth** [comment]
No, support for card.io has not been added yet. We're happy to review and merge any PRs for it though if you would like to contribute support for it.

**Comment by lkorth** [comment]
Support was added in 2.3.0, see the [section in the README](https://github.com/braintree/android-card-form#cardio) for more information.
