### ISSUE TITLE
how to hide card icon and hide filpflop hint text for card number

### ISSUE THREAD

**Issue by rmvivek** [braintree/android-card-form#50]

**Comment by quinnjn** [comment]
We don't offer the ability to hide the card icon. Would you be able to give a use case to hide the card icon?

I'm not to sure what you mean by "flipflop hint text for card number" can you give us some more details?

**Comment by quinnjn** [comment]
I'm going to close this issue due to inactivity. Please comment on it with some more details and we'll re-open it.
