### ISSUE TITLE
Card.io scan only card number but not Expiration date.

### ISSUE THREAD

**Issue by zgeorgiev** [braintree/android-card-form#55]
### General information
I integrated the card form together with card.io api but when I trigger card.io and scan a credit card it 
recognized only card number but not the expiration period. Any ideas?

minSdkVersion 16
targetSdkVersion 28 
Card.IO library version: api 'io.card:android-sdk:5.5.1'

Device: Samsung Galaxy S8 with Android 8.0

**Comment by quinnjn** [comment]
It sounds like your question is more directed at CardIO, and it might be worth opening a issue in that repository: https://github.com/card-io/card.io-Android-source

As far as android-card-form, it will accept a [CardIO result with a expiration date if the result is valid](https://github.com/braintree/android-card-form/blob/0af7aec2506f7279fa0193dd0b5bc2da15a2c392/CardForm/src/main/java/com/braintreepayments/cardform/view/CardForm.java#L382-L385). It could be that the CardIO result doesn't have a valid expiration.

I don't think there are any action items for your issue in this repository so I'm going to close the issue.
