### ISSUE TITLE
how to get card image bitmap

### ISSUE THREAD

**Issue by mrgogomaster** [braintree/android-card-form#59]
### General information

* SDK/Library version: 
* Android Version and Device:

**Comment by quinnjn** [comment]
I'm not to sure I understand the question. Please leave a comment with more detail on your question.

If you're asking how we get the card images in CardForm, they are available via the [CardForm's drawable resource folders](https://github.com/braintree/android-card-form/tree/master/CardForm/src/main/res/drawable-xxxhdpi).

**Comment by mrgogomaster** [comment]
we can get card number using String cardNumber = cardForm.getCardNumber();
is there any method to get bitmap of cardIcon
