### ISSUE TITLE
can we make only last four digit visible on getting card number

### ISSUE THREAD

**Issue by mrgogomaster** [braintree/android-card-form#60]

**Comment by quinnjn** [comment]
Are you asking how to get the last 4 digits of the card entered in the Card Form?

That can be achieved like this:
```
String cardNumber = cardForm.getCardNumber();
String last4 = cardNumber.substring(cardNumber.length() - 4);
```

If I misunderstood the question, please comment with more detail.

**Comment by mrgogomaster** [comment]
yes thats what i was asking thanks
