### ISSUE TITLE
Validate callback

### ISSUE THREAD

**Issue by lyfm** [braintree/android-card-form#69]
Could you please add callback for validation fields
So it will check the state before saving

**Comment by quinnjn** [comment]
I'm not to sure I understand the request fully. 

Are you looking for an overall validation callback? We do have [OnCardFormValidListener](https://github.com/braintree/android-card-form/blob/master/CardForm/src/main/java/com/braintreepayments/cardform/OnCardFormValidListener.java) for this purpose.

If that is not what you meant, can you give an example of what you're looking for?

**Comment by quinnjn** [comment]
I'm going to close this issue due to inactivity. Please comment on it with some more details and we'll re-open it.
