### ISSUE TITLE
Unable to pre-fill card on file information

### ISSUE THREAD

**Issue by chris-snader** [braintree/android-card-form#72]
* SDK/Library version: 4.1.0
* Android Version and Device: Pixel 2 OS 9.0

We store credit card information on our server and I would like to use that stored information to pre-fill the credit card form. Why are there no setter methods to accomplish this? Or is there another way that I can fill the form with all the stored credit card information?

**Comment by quinnjn** [comment]
Hi @chris-snader 

The purpose of Android Card Form is to get access to card information. If you already have those card details, why do you need to put them back into a card form? The only reason I can think of is editing a card which doesn't seem to align with where we want to take this library.

You could probably insert it by accessing and setting text on the fields manually:
```
CardForm cardForm = (CardForm) findViewById(R.id.card_form);

// Apply the card number to the card number field
((CardEditText)findViewById(R.id.bt_card_form_card_number)).setText("4111");
```

If that doesn't work feel free to fork the library and modify it to what you need!
