### ISSUE TITLE
Layout order

### ISSUE THREAD

**Issue by LipeDuoli** [braintree/android-card-form#75]
### General information

* SDK/Library version: 4.2.0

### Issue description

There is a way to change fields order? I want to add Name at last position
![card_form_OutlinedBox](https://user-images.githubusercontent.com/5374362/57383651-8952ba00-7185-11e9-84c7-3adf3be2a9d4.png)

**Comment by scannillo** [comment]
Hello @LipeDuoli . Currently, the way to achieve re-ordering the fields would be for you to fork the repo and manually re-arrange them yourself. 

Feel free to give us more information on your use case so we can determine if this is something we should consider implementing! Thanks.

**Comment by quinnjn** [comment]
@LipeDuoli you can redefine the [layout xml file](https://github.com/braintree/android-card-form/blob/master/CardForm/src/main/res/layout/bt_card_form_fields.xml) in your res folder and change the order how you wish. 

I don't think the CardForm has any logic expecting a specific order so you should be OK. If you do run into trouble though feel free to comment here and we'll see if we can address it.

**Comment by quinnjn** [comment]
Here is an example of reordering the fields: https://github.com/quinnjn/android-card-form-issue-75

This is how it is done: https://github.com/quinnjn/android-card-form-issue-75/commit/cc1d80bbfd30630cd4d3b6dbbedbc93317da737a

**Comment by LipeDuoli** [comment]
@scannillo the problem I'm having in my app is because users are starting typing the card number on first field without seeing anything else, and searching on several other apps that has card register, the first field is almost always the card number. So rearranging the fields, I can provide the best usability for my users.

@quinnjn thx for this tip, but reordering with this way has a little usability issue because the `setOnCardFormSubmitListener` still called after CVV field and not the name, that now is the last field on form.
I think i can add some workaround on code but is not the best way to do..
