### ISSUE TITLE
Suggestions on potential new fields

### ISSUE THREAD

**Issue by yuanliu666** [braintree/android-card-form#76]
Hi first thanks for the hard work! This library is really slick!
But then for my own projects, I often found myself needs more fields than what this one offers. Those are:
+ Email address;
+ Physical address bundle, could be address line 1, address line 2, city, state, country etc.

It would be really nice if you can add those! 
Thanks again.

**Comment by quinnjn** [comment]
Thank you!

Those fields don't seem to align well with a "card form" UI. They're kinda related but we're hoping to keep this as a pure card form entry UI.

You're more than welcome to fork this library if you want to add extra fields to it!
