### ISSUE TITLE
"Google Services" charge for 0.00 on creditcard without any processing

### ISSUE THREAD

**Issue by lucasjmiles** [braintree/android-card-form#77]
### General information

* SDK/Library version: 
* Android Version and Device: 

### Issue description

on card submit, or possibly during autofill (creditcard data) on Android 9, with embedded card form. Seems I am being charge $0.00 on my credit card when I haven't attempted to send payment data to any post processing scripts. What is going on?

**Comment by scannillo** [comment]
Hello. Pulling this repo and running its demo app should not charge your credit card. I have a feeling you are confusing this with another integration of yours. 

If you need assistance in setting up your sandbox and production credentials properly, contact Braintree Support at https://help.braintreepayments.com/
or 877.434.2894.
