### ISSUE TITLE
Screen Recording the Cardform 

### ISSUE THREAD

**Issue by damolaobaleke** [braintree/android-card-form#81]
### General information

* SDK/Library version: <'com.braintreepayments:card-form:4.2.0'>
* Android Version and Device: <Samsung Galaxy A30s with Android 9.0 >

### Issue description

Trying to allow screen recording of card-form, but cant screen shot or screen record "**due to security poilcy**"(The toast message comes up), is there a way to bypass this please, I've checked android permissions and haven't seen a way. So i know its in built in the API and cardform src code

**Comment by damolaobaleke** [comment]
How to clear the Flag

**Comment by lkorth** [comment]
https://github.com/braintree/android-card-form/blob/4136db746f4743a81b674217e40b85504a6e41a2/Sample/src/main/java/com/braintreepayments/sample/BaseCardFormActivity.java#L51-L53
