### ISSUE TITLE
Is there language support?

### ISSUE THREAD

**Issue by lcsvcn** [braintree/android-card-form#84]
It should be nice to have support to more than one language. I did not found, if there already is.

If isn't I is possible to add? I can help with the translation

**Comment by scannillo** [comment]
Hi. We do offer various language support. The currently translated languages are located [here](https://github.com/braintree/android-card-form/tree/master/CardForm/src/main/res). These translations will get updated according to the [device's locale](https://developer.android.com/guide/topics/resources/localization).

We support the languages that PayPal official supports and cannot support language translation PRs.
