### ISSUE TITLE
Retrieving the saved card

### ISSUE THREAD

**Issue by androuino** [braintree/android-card-form#85]
Hi,

I would like to ask if how to retrieve the saved card information if the checkbox for saving the card is checked? Seems like it hasn't been explained from the READMe file. Thanks.

**Comment by sestevens** [comment]
Hi @androuino, you can use the `getPaymentMethodNonces` method defined in the [`PaymentMethod` class](https://www.javadoc.io/doc/com.braintreepayments.api/braintree/latest/com/braintreepayments/api/PaymentMethod.html) to retrieve a customer's saved cards. You'll need to use a client token with a customer id when initializing the `BraintreeFragment`.

**Comment by androuino** [comment]
I see, thanks a lot @sestevens. Closing this now.
