### ISSUE TITLE
Autofill from Google Payments makes the card INVALID, because of wrong formating in EXPIRATION DATE

### ISSUE THREAD

**Issue by pesjak** [braintree/android-card-form#88]
### General information

* SDK/Library version: 4.2.0
* Android Version and Device:  OnePlus 6T Android 10

### Issue description

When using autofill from Google Payment, the expiration date gets wrong formatting, making the card NOT valid. 
Example:
10/ /24 ---> (should be) 10 / 24

**Comment by scannillo** [comment]
Hi @pesjak - can you include steps to help us reproduce your issue, along with screenshots of the issue you see?

**Comment by pesjak** [comment]
I can't include the screenhost, because the phone forbides it, because it is "sensitive" screen. 

Steps are:
1. Click on the empty box, where you enter the card number 
2. (Pops up selection from autofill) Select your card
3. Enter CVC code from that card (Google Payments Dialog)
4. Confirm the entered code (Google Payments Dialog)
5. Everything gets filled (Number, Date (double slashes) , CVC)

Additional: 
If you click on DATE, you will get keyboard where MONTH is selected but YEAR isn't.

**Comment by sshropshire** [comment]
Hi @pesjak are you able to take a picture of the screen with another phone?

**Comment by pesjak** [comment]
![received_1426883560824201](https://user-images.githubusercontent.com/7223498/82241341-47358a00-993c-11ea-97b8-127c56507eaa.jpeg)

**Comment by sshropshire** [comment]
@pesjak thank you. To confirm, does this issue occur in the repo's "Sample" application?

**Comment by pesjak** [comment]
Yes, I checked thed Sample app and the issue remains.

**Comment by sshropshire** [comment]
@pesjak awesome thank you. We are looking into this issue and will report back here when we have a solution.
