### ISSUE TITLE
name in form

### ISSUE THREAD

**Issue by dhavalsharma** [braintree/android-card-form#9]
Hi,

Is there a plan to add full name in form ?

thx

**Comment by lkorth** [comment]
@dhavalsharma the form is pretty extensible and you can easily create an `EditText` that extends `FloatingLabelEditText` and get the same appearance for free. You can also add some additional validations to your `EditText` if you wish. There are currently no plans to add an additional field like name, however pull requests are welcome.

**Comment by dhavalsharma** [comment]
thx @lkorth

**Comment by TheLester** [comment]
@lkorth  Can you please explain why FloatingLabelEditText must be wrapped in ViewGroup. Its seems like some ugly hack

**Comment by lkorth** [comment]
There was a conflict with the view and it's parent view.
