### ISSUE TITLE
 Option of number of installments payable.

### ISSUE THREAD

**Issue by Daniels-123** [braintree/android-card-form#91]
This Library is Amazing ! but I have this problem with the  the number of installments payable

**Comment by scannillo** [comment]
Hi @Daniels-123. Thanks for using android-card-form! 

Is this a feature request? If so - can you elaborate more on what you're asking for and what you mean by _number of installments payable_?

**Comment by Daniels-123** [comment]
Hello @scannillo , thank you for answering this thread, I explain clearly, in some countries it is possible to choose how many monthly payments of the debt you are acquiring, it is possible to choose it from 1 to 48 monthly installments

**Comment by Epreuve** [comment]
@Daniels-123 The card form only provides a method of collecting payment details, and does not itself create a transaction/charge.  

If you'd like to allow a customer to pay for a product in installments, that would be something handled independently by your app and/or your backend server.
