### ISSUE TITLE
Expiration date sheet style issues on Android 11 beta

### ISSUE THREAD

**Issue by alashow** [braintree/android-card-form#93]
### General information

* SDK/Library version: 4.3.0
* Android Version and Device: tried on Pixel 3 XL and Android emulator running on Android 11 Beta. It looked as expected in an emulator running on API 21.

### Issue description

1.  It doesn't take the full width
2. The year rows don't fit in one line (I guess because of ^)
3. There is a black line/block below the sheet.

<img width="400" alt="Screen Shot 2020-06-21 at 2 47 54 AM" src="https://user-images.githubusercontent.com/5840013/85219507-fc0efc80-b369-11ea-9d25-f829c4968061.png">

**Comment by sshropshire** [comment]
Hi @alashow thanks for using the Braintree SDK for Android. We're looking into this issue and will provide an update once we have a solution.

As a workaround, you can disable the date picker dialog in favor of a numeric keypad. To do so, after calling `mCardForm.setup()`, then call:
```
mCardForm.getExpirationDateEditText().useDialogForExpirationDateEntry(this, false);
``` 
This will enable the Android system keyboard.

**Comment by sshropshire** [comment]
Date picker dialog is now deprecated in v5.0.0. The expiration date field now leverages the numeric keyboard.
